/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 11-Oct-2023 16:01:51
 */

/*
 * 离散时间 FIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接型 FIR
 * 滤波器长度  : 24
 * 稳定     : 是
 * 线性相位   : 是 (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Program Files\MATLAB\R2022b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 24;
const int16_T B[24] = {
     1301,   1317,   1332,   1346,   1359,   1369,   1379,   1387,   1393,
     1398,   1401,   1402,   1402,   1401,   1398,   1393,   1387,   1379,
     1369,   1359,   1346,   1332,   1317,   1301
};
