/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 22-Aug-2023 14:02:32
 */

/*
 * 离散时间 FIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接型 FIR
 * 滤波器长度  : 48
 * 稳定     : 是
 * 线性相位   : 是 (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Program Files\MATLAB\R2022b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 48;
const int16_T B[48] = {
      103,    108,    124,    150,    186,    230,    283,    344,    410,
      482,    558,    636,    715,    793,    870,    944,   1014,   1077,
     1134,   1183,   1224,   1254,   1275,   1286,   1286,   1275,   1254,
     1224,   1183,   1134,   1077,   1014,    944,    870,    793,    715,
      636,    558,    482,    410,    344,    283,    230,    186,    150,
      124,    108,    103
};
